age1=int(input("Enter your age for person 1="))
age2=int(input("Enter your age for person 2="))
age3=int(input("Enter your age for person 3="))
age4=int(input("Enter your age for person 4="))
old=max(age1,age2,age3,age4)
print(f"The oldest age is{old}")